<a href="https://colab.research.google.com/github/kovacova/random-magic/blob/master/projects/07-numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np

In [0]:
a = np.mat('4 3 ; 2 1')
a

matrix([[4, 3],
        [2, 1]])

In [0]:
print('Transpose \n', a.T)

Transpose 
 [[4 2]
 [3 1]]


In [0]:
print('Inverse \n', a.I)

Inverse 
 [[-0.5  1.5]
 [ 1.  -2. ]]


# Numpy Linalg - Linear Algebra Library for Numpy

In [0]:
# Numpy Linalg - Linear Algebra Library for Numpy

c = np.asmatrix(df['column_1', 'column_2'])

# @ - Python's Matrix Multiplication Operator


PEP 465 introduced the @ infix operator that is designated to be used for matrix multiplication.

🔗[Tutorial](https://alysivji.github.io/python-matrix-multiplication-operator.html)

In [0]:
import numpy as np

In [4]:
A = np.matrix('3 1; 7 9')
A

matrix([[3, 1],
        [7, 9]])

In [5]:
B = np.matrix('6 1; 7 9')
B

matrix([[6, 1],
        [7, 9]])

In [6]:
# Performs Matrix Multiplication Beautifully
A @ B

matrix([[ 25,  12],
        [105,  88]])